
-- 1 -----------------------------------------------------------------
-- NEGOCIO
-- CREACION DE TABLONES CON CASTEO Y JOIN DE TABLAS DIMENSIONES

-----------------------
--TABLON F_VENTAS_DESC
-----------------------

CREATE EXTERNAL TABLE NEGOCIO.F_VENTAS_DESC(
ID_BOLETA STRING COMMENT 'Numero de Comprobante autogenerado - Control Interno',
ID_CLIENTE STRING COMMENT 'Codigo de Cliente',
NOMBRE_C STRING COMMENT 'Nombre de Cliente',
APELLIDO_C STRING COMMENT 'Apellido de Cliente',

ID_CAJA STRING COMMENT 'Codigo de Caja',
NUMEROCAJA STRING COMMENT 'Numero de Caja',
DEPARTAMENTO STRING COMMENT 'Ubicacion Departamento de Caja',
PROVINCIA STRING COMMENT 'Ubicacion Provincia de Caja',
DISTRITO STRING COMMENT 'Ubicacion Distrito de Caja',

NRO_TRANSACCION STRING COMMENT 'Numero de Transaccion',
TIPO_MONEDA STRING COMMENT 'Tipo de Moneda',
TIPO_COMPROBANTE STRING COMMENT 'Tipo de Comprobante',

ID_VENDEDOR STRING COMMENT 'Codigo de Vendedor',
NOMBRE_V STRING COMMENT 'Nombre del Vendedor',
APELLIDO_PATERNO_V STRING COMMENT 'Apellido Paterno de Cliente',
APELLIDO_MATERNO_V STRING COMMENT 'Apellido Materno de Cliente',

NRO_SERIE STRING COMMENT 'Numero de Serie de Comprobate - Tributario',

ID_PRODUCTO STRING COMMENT 'Codigo de Producto',
NOMBRE_PRODUCTO STRING COMMENT 'Nombre de Producto',
CATEGORIA STRING COMMENT 'Categoria de Producto',
MARCA STRING COMMENT 'Marca de Producto',
PRECIO STRING COMMENT 'Precio de Producto',

ID_FECHA STRING COMMENT 'Codigo de Fecha de Impresion de Comprobante',
ANO INT COMMENT 'Año de impresion de Comprobante',
MES STRING COMMENT 'Mes de Impresion de Comprobante',
DIA INT COMMENT 'Dia de Impresion de Comprobante',
HORA STRING COMMENT 'Hora de Impresion de Comprobante',

PRECIO_VENTA DOUBLE COMMENT 'Precio Unitario de Producto',
CANTIDAD DOUBLE COMMENT 'Cantidad de Productos',
MODALIDAD_COMPRA STRING COMMENT 'Modalidad de Compra',
TOTAL DOUBLE COMMENT 'Precio total Pagado'
)
STORED AS PARQUET
LOCATION '/DATAMART_VENTAS/NEGOCIO/F_VENTAS_DESC'
TBLPROPERTIES ('creator'='ing_delivery', 'created_at'='2021-04-27');


-- MAPREDUCE ENGINE
SET hive.execution.engine=mr;

--JOIN PARA SUBIR DATA A F_VENTAS_DESC

INSERT OVERWRITE TABLE NEGOCIO.F_VENTAS_DESC
SELECT
FV.ID_BOLETA,
FV.ID_CLIENTE,
CL.NOMBRE,
CL.APELLIDO,

FV.ID_CAJA,
CJ.NUMEROCAJA,
LC.DEPARTAMENTO,
LC.PROVINCIA,
LC.DISTRITO,

FV.NRO_TRANSACCION,
FV.TIPO_MONEDA,
FV.TIPO_COMPROBANTE,

FV.ID_VENDEDOR,
VN.NOMBRE,
VN.APELLIDO_PATERNO,
VN.APELLIDO_MATERNO,

FV.NRO_SERIE,

FV.ID_PRODUCTO,
PR.NOMBRE_PRODUCTO,
CA.CATEGORIA,
MC.MARCA,
PR.PRECIO,

FV.ID_FECHA,
CAST(ANO AS INT),
MES STRING,
CAST(DIA AS INT),
HORA STRING,

CAST(PRECIO_VENTA as DOUBLE),
CAST(CANTIDAD AS INT),
MODALIDAD_COMPRA STRING,
CAST(TOTAL AS DOUBLE)

FROM 
OPERACIONAL.F_VENTAS_PARQUET FV
JOIN NEGOCIO.D_CLIENTE CL 
ON (FV.ID_CLIENTE=CL.ID_CLIENTE)
JOIN negocio.D_CAJA CJ 
ON (FV.ID_CAJA=CJ.ID_CAJA)
JOIN negocio.D_VENDEDOR VN 
ON (FV.ID_VENDEDOR=VN.ID_VENDEDOR)
JOIN negocio.D_PRODUCTO PR 
ON (FV.ID_PRODUCTO=PR.ID_PRODUCTO)
JOIN negocio.D_CATEGORIA CA 
ON (PR.ID_CATEGORIA=CA.ID_CATEGORIA)
JOIN negocio.D_MARCA MC 
ON (PR.ID_MARCA=MC.ID_MARCA)
JOIN negocio.D_LOCAL LC 
ON (CJ.ID_LOCAL=LC.ID_LOCAL)
JOIN negocio.D_FECHA FC 
ON (FV.ID_FECHA=FC.ID_FECHA)
JOIN negocio.D_ANO AN 
ON (FC.ID_ANO=AN.ID_ANO)
JOIN negocio.D_MES MS 
ON (FC.ID_MES=MS.ID_MES)
JOIN negocio.D_DIA DI 
ON (FC.ID_DIA=DI.ID_DIA)
JOIN NEGOCIO.D_HORA HR
ON (FC.ID_HORA=HR.ID_HORA);


-- DEFAULT ENGINE
--SET hive.execution.engine=tez;
	
----------------------------------
--TABLON F_STOCK_INVENTARIO_DESC
----------------------------------

CREATE EXTERNAL TABLE NEGOCIO.F_STOCK_INVENTARIO_DESC(
ID_STOCK_INVENTARIO STRING COMMENT 'Autogenerado de Registro en Stock Inventario',
ID_PRODUCTO STRING COMMENT 'Codigo de Producto',
NOMBRE_PRODUCTO STRING COMMENT 'Nombre de Producto',
CATEGORIA STRING COMMENT 'Categoria de Producto',
MARCA STRING COMMENT 'Marca de Producto',
PRECIO DOUBLE COMMENT 'Precio Unitario de Producto',
LOTE STRING COMMENT 'Codigo de Lote de Producto',
FECHA_VENCIMIENTO STRING COMMENT 'Fecha Vencimiento de Lote',
STOCK_MINIMO INT COMMENT 'Cantidad Minima por Producto a tener en Almacen',
TOTAL INT COMMENT 'Stock total y actualizada por producto'
)
STORED AS PARQUET
LOCATION '/DATAMART_VENTAS/NEGOCIO/F_STOCK_INVENTARIO_DESC'
TBLPROPERTIES ('creator'='ing_delivery', 'created_at'='2021-04-27');


--JOIN PARA SUBIR DATA A F_STOCK_INVENTARIO_DESC

INSERT OVERWRITE TABLE NEGOCIO.F_STOCK_INVENTARIO_DESC  
SELECT 
FSI.ID_STOCK_INVENTARIO,
FSI.ID_PRODUCTO,
DPR.NOMBRE_PRODUCTO,
DCA.CATEGORIA,
DMA.MARCA,
CAST(DPR.PRECIO AS DOUBLE),
FSI.LOTE,
FSI.FECHA_VENCIMIENTO,
CAST(FSI.STOCK_MINIMO AS INT),
CAST(FSI.TOTAL AS INT)
FROM 
OPERACIONAL.F_STOCK_INVENTARIO_PARQUET FSI
JOIN NEGOCIO.D_PRODUCTO DPR 
ON (FSI.ID_PRODUCTO=DPR.ID_PRODUCTO)
JOIN NEGOCIO.D_CATEGORIA DCA 
ON (DPR.ID_CATEGORIA=DCA.ID_CATEGORIA)
JOIN NEGOCIO.D_MARCA DMA 
ON (DPR.ID_MARCA=DMA.ID_MARCA);

