-- 1 -----------------------------------------------------------------
-- NEGOCIOS
--Creacion de base de datos de NEGOCIO
CREATE DATABASE IF NOT EXISTS NEGOCIO
COMMENT 'BASE DE DATOS NEGOCIO'
LOCATION 'DATAMART_VENTAS/NEGOCIO'
WITH DBPROPERTIES('creator'='ING DELIVERY','date'='2021-04-25');

--------------
--D_PRODUCTO
--------------
CREATE EXTERNAL TABLE NEGOCIO.D_PRODUCTO LIKE OPERACIONAL.D_PRODUCTO_PARQUET
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_PRODUCTO'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_PRODUCTO
SELECT *
FROM OPERACIONAL.D_PRODUCTO_PARQUET;

------------
--D_MARCA
------------
CREATE EXTERNAL TABLE NEGOCIO.D_MARCA LIKE OPERACIONAL.D_MARCA_PARQUET
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_MARCA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_MARCA
SELECT *
FROM OPERACIONAL.D_MARCA_PARQUET;


---------------
--D_CATEGORIA
---------------
CREATE EXTERNAL TABLE NEGOCIO.D_CATEGORIA LIKE OPERACIONAL.D_CATEGORIA_PARQUET 
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_CATEGORIA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_CATEGORIA
SELECT *
FROM OPERACIONAL.D_CATEGORIA_PARQUET;


-------------
--D_CLIENTE
-------------
CREATE EXTERNAL TABLE NEGOCIO.D_CLIENTE LIKE OPERACIONAL.D_CLIENTE_PARQUET 
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_CLIENTE'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_CLIENTE
SELECT *
FROM OPERACIONAL.D_CLIENTE_PARQUET;


--------------
--D_VENDEDOR
--------------
CREATE EXTERNAL TABLE NEGOCIO.D_VENDEDOR LIKE OPERACIONAL.D_VENDEDOR_PARQUET 
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_VENDEDOR'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_VENDEDOR
SELECT *
FROM OPERACIONAL.D_VENDEDOR_PARQUET;


------------------
--D_FECHA
------------------
CREATE EXTERNAL TABLE NEGOCIO.D_FECHA LIKE OPERACIONAL.D_FECHA_PARQUET
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_FECHA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_FECHA
SELECT *
FROM OPERACIONAL.D_FECHA_PARQUET;


-----------------
--D_ANO
-----------------
CREATE EXTERNAL TABLE NEGOCIO.D_ANO LIKE OPERACIONAL.D_ANO_PARQUET 
STORED AS PARQUET
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_ANO'
TBLPROPERTIES ('creator'='ing_delivery', 'created_at'='2021-04-25');

INSERT OVERWRITE TABLE NEGOCIO.D_ANO
SELECT *
FROM OPERACIONAL.D_ANO_PARQUET;


-----------------
--D_MES
-----------------
CREATE EXTERNAL TABLE NEGOCIO.D_MES LIKE OPERACIONAL.D_MES_PARQUET
STORED AS PARQUET
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_MES'
TBLPROPERTIES ('creator'='ing_delivery', 'created_at'='2021-04-25');

INSERT OVERWRITE TABLE NEGOCIO.D_MES
SELECT *
FROM OPERACIONAL.D_MES_PARQUET;


-----------------
--D_DIA
-----------------
CREATE EXTERNAL TABLE NEGOCIO.D_DIA LIKE OPERACIONAL.D_DIA_PARQUET
STORED AS PARQUET
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_DIA'
TBLPROPERTIES ('creator'='ing_delivery', 'created_at'='2021-04-25');

INSERT OVERWRITE TABLE NEGOCIO.D_DIA
SELECT *
FROM OPERACIONAL.D_DIA_PARQUET;


-----------------
--D_HORA
-----------------
CREATE EXTERNAL TABLE NEGOCIO.D_HORA LIKE OPERACIONAL.D_HORA_PARQUET 
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_HORA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_HORA
SELECT *
FROM OPERACIONAL.D_HORA_PARQUET;


------------------
--D_LOCAL
------------------
CREATE EXTERNAL TABLE NEGOCIO.D_LOCAL LIKE OPERACIONAL.D_LOCAL_PARQUET 
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_LOCAL'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_LOCAL
SELECT *
FROM OPERACIONAL.D_LOCAL_PARQUET;


------------------
--D_CAJA
------------------
CREATE EXTERNAL TABLE NEGOCIO.D_CAJA LIKE OPERACIONAL.D_CAJA_PARQUET 
STORED AS PARQUET 
LOCATION '/DATAMART_VENTAS/NEGOCIO/D_CAJA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

INSERT OVERWRITE TABLE NEGOCIO.D_CAJA
SELECT *
FROM OPERACIONAL.D_CAJA_PARQUET;
