-- VISTA 1 --
-- PRODUCTOS SEGUN CANTIDAD Y MONTO VENDIDO EN EL AÑO 2021

CREATE VIEW NEGOCIO.V_VENTAS_PRODUCTOS
AS
SELECT 
NOMBRE_PRODUCTO,
COUNT(*) AS N_VENTAS,
SUM(TOTAL) AS VENTA_TOTAL
FROM NEGOCIO.F_VENTAS_DESC
WHERE ANO = '2021'
GROUP BY NOMBRE_PRODUCTO;

-- VISTA 2
-- QUIENES SON LOS CLIENTES MAS FRECUENTES
CREATE VIEW NEGOCIO.V_CLIENTES_FRECUENTES
AS
SELECT 
NOMBRE_C,
COUNT(*) AS N_COMPRAS
FROM NEGOCIO.F_VENTAS_DESC
GROUP BY NOMBRE_C
ORDER BY N_COMPRAS DESC;

--VISTA 3
-- INGRESO BRUTO POR VENTAS MENSUAL
CREATE VIEW NEGOCIO.V_INGRESO_MENSUAL
AS
SELECT 
ANO,
MES,
SUM(TOTAL) AS VENTA_TOTAL
FROM NEGOCIO.F_VENTAS_DESC
GROUP BY ANO,MES;

--VISTA 4
-- CUALES SON LAS MARCAS MAS VENDIDAS
CREATE VIEW NEGOCIO.V_MARCAS_MASVENDIDAS
AS
SELECT 
MARCA,
COUNT(*) AS N_VENTAS
FROM NEGOCIO.F_VENTAS_DESC
GROUP BY MARCA
ORDER BY N_VENTAS DESC;

-- VISTA 5
-- CUAL ES LA MODALIDAD DE COMPRA QUE GENERA MAYOR INGRESOS
CREATE VIEW NEGOCIO.V_MODALIDAD
AS
SELECT 
MODALIDAD_COMPRA,
COUNT(*) AS N_VENTAS
FROM NEGOCIO.F_VENTAS_DESC
GROUP BY MODALIDAD_COMPRA
ORDER BY N_VENTAS DESC;

-- VISTA 6
-- QUE TIPO DE COMPROBANTE DE PAGO GENERA MAS INGRESOS
CREATE VIEW NEGOCIO.V_COMPROBANTE
AS
SELECT 
TIPO_COMPROBANTE,
COUNT(*) AS N_VENTAS
FROM NEGOCIO.F_VENTAS_DESC
GROUP BY TIPO_COMPROBANTE
ORDER BY N_VENTAS DESC;