beeline -u jdbc:hive2://

-- 5 -----------------------------------------------------------------
-- LANDING
-- CREACION DE BASE DATOS
CREATE DATABASE IF NOT EXISTS TEMPORAL
COMMENT 'BASE DE DATOS PARA LANDING'
LOCATION '/DATAMART_VENTAS/TEMPORAL'
WITH DBPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27');

-- 6 -----------------------------------------------------------------
--CREACION DE TABLAS EXTERNAS AVRO CON LOCATION

-------------------
--F_VENTAS_AVRO
-------------------
CREATE EXTERNAL TABLE TEMPORAL.F_VENTAS_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/F_VENTAS_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/F_VENTAS_AVRO.avsc');

CREATE TABLE TEMPORAL.F_VENTAS LIKE TEMPORAL.F_VENTAS_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/F_VENTAS'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/F_Ventas.csv' OVERWRITE INTO TABLE TEMPORAL.F_VENTAS;

INSERT OVERWRITE TABLE TEMPORAL.F_VENTAS_AVRO
SELECT * FROM  TEMPORAL.F_VENTAS WHERE ID_BOLETA != 'ID_BOLETA';

DROP TABLE TEMPORAL.F_VENTAS;


-------------------
--D_PRODUCTO_AVRO
-------------------
CREATE EXTERNAL TABLE TEMPORAL.D_PRODUCTO_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_PRODUCTO_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_PRODUCTO_AVRO.avsc');

CREATE TABLE TEMPORAL.D_PRODUCTO LIKE TEMPORAL.D_PRODUCTO_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_PRODUCTO'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Producto.csv' OVERWRITE INTO TABLE TEMPORAL.D_PRODUCTO;

INSERT OVERWRITE TABLE TEMPORAL.D_PRODUCTO_AVRO
SELECT * FROM  TEMPORAL.D_PRODUCTO WHERE ID_PRODUCTO != 'ID_PRODUCTO';

DROP TABLE TEMPORAL.D_PRODUCTO;


-------------------
--D_VENDEDOR_AVRO
-------------------
CREATE EXTERNAL TABLE TEMPORAL.D_VENDEDOR_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_VENDEDOR_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_VENDEDOR_AVRO.avsc');

CREATE TABLE TEMPORAL.D_VENDEDOR LIKE TEMPORAL.D_VENDEDOR_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_VENDEDOR'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Vendedor.csv' OVERWRITE INTO TABLE TEMPORAL.D_VENDEDOR;

INSERT OVERWRITE TABLE TEMPORAL.D_VENDEDOR_AVRO
SELECT * FROM  TEMPORAL.D_VENDEDOR WHERE ID_VENDEDOR != 'ID_VENDEDOR';

DROP TABLE TEMPORAL.D_VENDEDOR;


--------------------
--D_CATEGORIA_AVRO         *************************************
--------------------
CREATE EXTERNAL TABLE TEMPORAL.D_CATEGORIA_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_CATEGORIA_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_CATEGORIA_AVRO.avsc');

CREATE TABLE TEMPORAL.D_CATEGORIA LIKE TEMPORAL.D_CATEGORIA_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_CATEGORIA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Categoria.csv' OVERWRITE INTO TABLE TEMPORAL.D_CATEGORIA;

INSERT OVERWRITE TABLE TEMPORAL.D_CATEGORIA_AVRO
SELECT * FROM  TEMPORAL.D_CATEGORIA WHERE ID_CATEGORIA != 'ID_CATEGORIA';

DROP TABLE TEMPORAL.D_CATEGORIA;


-------------------
--D_MARCA_AVRO
-------------------
CREATE EXTERNAL TABLE TEMPORAL.D_MARCA_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_MARCA_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_MARCA_AVRO.avsc');

CREATE TABLE TEMPORAL.D_MARCA LIKE TEMPORAL.D_MARCA_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_MARCA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Marca.csv' OVERWRITE INTO TABLE TEMPORAL.D_MARCA;

INSERT OVERWRITE TABLE TEMPORAL.D_MARCA_AVRO
SELECT * FROM  TEMPORAL.D_MARCA WHERE ID_MARCA != 'ID_MARCA';

DROP TABLE TEMPORAL.D_MARCA;


---------------------------
--F_STOCK_INVENTARIO_AVRO
---------------------------
CREATE EXTERNAL TABLE TEMPORAL.F_STOCK_INVENTARIO_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/F_STOCK_INVENTARIO_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/F_STOCK_INVENTARIO_AVRO.avsc');

CREATE TABLE TEMPORAL.F_STOCK_INVENTARIO LIKE TEMPORAL.F_STOCK_INVENTARIO_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/F_STOCK_INVENTARIO'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/F_Stock_Inventario.csv' OVERWRITE INTO TABLE TEMPORAL.F_STOCK_INVENTARIO;

INSERT OVERWRITE TABLE TEMPORAL.F_STOCK_INVENTARIO_AVRO
SELECT * FROM  TEMPORAL.F_STOCK_INVENTARIO WHERE ID_STOCK_INVENTARIO != 'ID_STOCK_INVENTARIO';

DROP TABLE TEMPORAL.F_STOCK_INVENTARIO;


-------------------
--D_CLIENTE_AVRO
-------------------
CREATE EXTERNAL TABLE TEMPORAL.D_CLIENTE_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_CLIENTE_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_CLIENTE_AVRO.avsc');

CREATE TABLE TEMPORAL.D_CLIENTE LIKE TEMPORAL.D_CLIENTE_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_CLIENTE'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Cliente.csv' OVERWRITE INTO TABLE TEMPORAL.D_CLIENTE;

INSERT OVERWRITE TABLE TEMPORAL.D_CLIENTE_AVRO
SELECT * FROM  TEMPORAL.D_CLIENTE WHERE ID_CLIENTE != 'ID_CLIENTE';

DROP TABLE TEMPORAL.D_CLIENTE;


----------------
--D_CAJA_AVRO
----------------
CREATE EXTERNAL TABLE TEMPORAL.D_CAJA_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_CAJA_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_CAJA_AVRO.avsc');

CREATE TABLE TEMPORAL.D_CAJA LIKE TEMPORAL.D_CAJA_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_CAJA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Caja.csv' OVERWRITE INTO TABLE TEMPORAL.D_CAJA;

INSERT OVERWRITE TABLE TEMPORAL.D_CAJA_AVRO
SELECT * FROM  TEMPORAL.D_CAJA WHERE ID_CAJA != 'ID_CAJA';

DROP TABLE TEMPORAL.D_CAJA;


-----------------
--D_LOCAL_AVRO
-----------------
CREATE EXTERNAL TABLE TEMPORAL.D_LOCAL_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_LOCAL_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_LOCAL_AVRO.avsc');

CREATE TABLE TEMPORAL.D_LOCAL LIKE TEMPORAL.D_LOCAL_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_LOCAL'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Local.csv' OVERWRITE INTO TABLE TEMPORAL.D_LOCAL;

INSERT OVERWRITE TABLE TEMPORAL.D_LOCAL_AVRO
SELECT * FROM  TEMPORAL.D_LOCAL WHERE ID_LOCAL != 'ID_LOCAL';

DROP TABLE TEMPORAL.D_LOCAL;


-----------------
--D_FECHA_AVRO
-----------------
CREATE EXTERNAL TABLE TEMPORAL.D_FECHA_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_FECHA_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_FECHA_AVRO.avsc');

CREATE TABLE TEMPORAL.D_FECHA LIKE TEMPORAL.D_FECHA_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_FECHA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Fecha.csv' OVERWRITE INTO TABLE TEMPORAL.D_FECHA;

INSERT OVERWRITE TABLE TEMPORAL.D_FECHA_AVRO
SELECT * FROM  TEMPORAL.D_FECHA WHERE ID_FECHA != 'ID_FECHA';

DROP TABLE TEMPORAL.D_FECHA;


---------------
--D_ANO_AVRO
---------------
CREATE EXTERNAL TABLE TEMPORAL.D_ANO_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_ANO_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_ANO_AVRO.avsc');

CREATE TABLE TEMPORAL.D_ANO LIKE TEMPORAL.D_ANO_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_ANO'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Ano.csv' OVERWRITE INTO TABLE TEMPORAL.D_ANO;

INSERT OVERWRITE TABLE TEMPORAL.D_ANO_AVRO
SELECT * FROM  TEMPORAL.D_ANO WHERE ID_ANO != 'ID_ANO';

DROP TABLE TEMPORAL.D_ANO;


---------------
--D_MES_AVRO
---------------
CREATE EXTERNAL TABLE TEMPORAL.D_MES_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_MES_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_MES_AVRO.avsc');

CREATE TABLE TEMPORAL.D_MES LIKE TEMPORAL.D_MES_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_MES'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Mes.csv' OVERWRITE INTO TABLE TEMPORAL.D_MES;

INSERT OVERWRITE TABLE TEMPORAL.D_MES_AVRO
SELECT * FROM  TEMPORAL.D_MES WHERE ID_MES != 'ID_MES';

DROP TABLE TEMPORAL.D_MES;


---------------
--D_DIA_AVRO
---------------
CREATE EXTERNAL TABLE TEMPORAL.D_DIA_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_DIA_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_DIA_AVRO.avsc');

CREATE TABLE TEMPORAL.D_DIA LIKE TEMPORAL.D_DIA_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_DIA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Dia.csv' OVERWRITE INTO TABLE TEMPORAL.D_DIA;

INSERT OVERWRITE TABLE TEMPORAL.D_DIA_AVRO
SELECT * FROM  TEMPORAL.D_DIA WHERE ID_DIA != 'ID_DIA';

DROP TABLE TEMPORAL.D_DIA;


----------------
--D_HORA_AVRO
----------------
CREATE EXTERNAL TABLE TEMPORAL.D_HORA_AVRO
STORED AS AVRO
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_HORA_AVRO'
TBLPROPERTIES (
'avro.schema.url'='hdfs:///DATAMART_VENTAS/TEMPORAL/SCHEMA_AVRO/D_HORA_AVRO.avsc');

CREATE TABLE TEMPORAL.D_HORA LIKE TEMPORAL.D_HORA_AVRO
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS TEXTFILE 
LOCATION '/DATAMART_VENTAS/TEMPORAL/D_HORA'
TBLPROPERTIES ('creator'='ing_delivery', 'date'='2021-04-27', 'skip.header.line.count'='1');

LOAD DATA LOCAL INPATH 'datamart/dataset/D_Hora.csv' OVERWRITE INTO TABLE TEMPORAL.D_HORA;

INSERT OVERWRITE TABLE TEMPORAL.D_HORA_AVRO
SELECT * FROM  TEMPORAL.D_HORA WHERE ID_HORA != 'ID_HORA';

DROP TABLE TEMPORAL.D_HORA;



